# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d65db146637b303077cb1c04283545644b1a795410b43465a9baaf600b6f49a47b35d735e18b986dc55234fbdfecae648a7a981df180c1fe11bddbe11a35c263

test:
  secret_key_base: 5e5a67d67e9c7eabead2bf0996e0008a938272482622dddf505dd0b8f6223180112d37b5e3edbcd941b7279801455da85cc341e4495fe8deac51f72b366ade3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
